### ISSUE TITLE
Output enthalpy values not matching expected values

### ISSUE THREAD

**Issue by cjholdship** [VlachosGroup/PythonGroupAdditivity#12]
I'm running your example script for C1CO1 but for other simple hydrocarbons such as methanol and propane and comparing the numbers outputted from the script and those published in Benson's Thermochemical Kinetics. There seems to be a large disparity between the two as for methanol the outputted value is -80.65 kcal/mol whereas the published value is -48 kcal/mol. Can you please provide either a reason or a fix if possible?

**Comment by cjholdship** [comment]
Fixed by using get_H() and specifying units of kcal/mol instead of using get_HoRT.

**Comment by wittregr** [comment]
Sorry I missed your earlier issue post...Getting ready for AIChE in Orlando! You are correct if you use the method get_HoRT (Literally means H over RT) then you get a dimensionless enthalpy. The method get_H with units specified will give you enthalpy in the chosen units. The same is true of each thermodynamic quantity. If you use the dimensionless method you can also use the pMuTT constants function to convert to desired units. This can be useful if your calculation requires dimensionless but you would like to plot/print with dimensions.
```
import pmutt.constants as c
HoRT = <object>.get_HoRT(298.15)
H = HoRT * c.R('kcal/mol/K') * 298.15
print(H, ' [kcal/mol]')
```
