### ISSUE TITLE
Typo in corrections.yaml

### ISSUE THREAD

**Issue by cjholdship** [VlachosGroup/PythonGroupAdditivity#13]
Gauche spelt as Gacueh in both 'AlkaneGauche' and 'AlkeneGauche' groups in the corrections file found in BensonsGA. 
Causes missing group errors when testing hydrocarbons.

**Comment by wittregr** [comment]
Thanks for the feedback. I'm surprised this bug hasn't been discovered in the past. I corrected the problem and have published v1.6. Use pip install --upgrade pgradd to install the new version.

**Comment by cjholdship** [comment]
Gauche still spelt incorrectly this time as 'Gauech' instead of Gauche
