### ISSUE TITLE
Update to Python 3.10: need to change Mapping import

### ISSUE THREAD

**Issue by ericchen-udel** [VlachosGroup/PythonGroupAdditivity#20]
For use in Python 3.10:
Mapping import needs to be changed from:

from collections import Mapping

to

from collections.abc import Mapping

In:
GroupAdd/Library.py
yaml.io/schema.py
yaml.io/builtins.py

**Comment by wittregr** [comment]
Thanks, Eric. I appreciate the detail you included. The changes are made and will appear in the next pGrAdd version (>3.9.5).
