### ISSUE TITLE
get_S method for lib entries goes to incomplete.py method, which requires additional S_elements inputs

### ISSUE THREAD

**Issue by ericchen-udel** [VlachosGroup/PythonGroupAdditivity#21]
I am getting the BensonGA entropy values (for which they exist). I ran into an issue for the following code:

lib = GroupLibrary.Load('BensonGA')
lib_dict = dict()

for i in lib.items():
    print(i[0].name)
    lib_dict[i[0].name] = {'H': i[1]['thermochem'].get_H(298.15, 'kcal/mol'),
                           'S': i[1]['thermochem'].get_S(298.15, 'cal/mol/K')}

*** TypeError: ThermochemIncomplete.get_SoR() got an unexpected keyword argument 'S_elements'

The 'thermochem' object is drawing from incomplete.py, whose method .get_S does not have an 'S_elements' keyword input. 

The issue was resolved by adding in the file "incomplete.py", on line 165, S_elements=S_elements into the method .get_SoR 

I am not sure where else this S_elements may need to be included as well.

**Comment by wittregr** [comment]
Complete.
