### ISSUE TITLE
SMARTS/SMILES

### ISSUE THREAD

**Issue by pythonnewbie3** [VlachosGroup/PythonGroupAdditivity#23]
Hi, where do you store the group data and extract it from the smiles string for Bensons group additivity theory?
Kind regards

**Comment by wittregr** [comment]
The pgradd directory has a data directory where all the group contribution values for each scheme are stored. You can view this data here on Github or in your installed copy of pgradd.  In our BensonGA database, there are several .yaml files that contain that scheme's group contribution values. The directory structure is shown below. All .yaml files except library.yaml and scheme.yaml contain group contribution values. The values used come from Bensons's papers cited on our Github page. For more information about all these files, please, read our paper in Physics Computer Communication cited on our Githib page.

data
  |-BesnonGA
      |-gas_benson
         |-corrections.yaml
         |-extra.yaml
         |-hydrocarbons.yaml
         |-hydrocarbons_original.yaml
         |-index.yaml
         |-notrogentaes.yaml
         |-original.yaml
         |-oxygenates.yaml
         |-radicals.yaml
         |-strain.yaml
      |-library.yaml
      |-scheme.yaml
      |-surface_benson.lib.yaml
