### ISSUE TITLE
Interface with pMuTT

### ISSUE THREAD

**Issue by jonlym** [VlachosGroup/PythonGroupAdditivity#4]
Currently, to use VGA with pMuTT, the VGA object must be converted to a Nasa or Shomate object. However, we could cut out this step if we renamed VGA's methods to pMuTT's format (i.e. `eval_ND_H` to `get_HoRT`).

Dimensional methods (e.g. `get_H`) would also be useful. I suggest adding pMuTT as a dependency so that the `pMuTT.constants` module is accessible to VGA.

**Comment by wittregr** [comment]
VGA (v1.3.3) now has new thermochemical evaluation methods aligned with pMuTT.  `get_HoRT(T)`, `get_SoR(T)`, `get_GoRT(T)`, and `get_CpoR(T)` for dimensionless quantities. In addition, four new dimensional methods have also been added. `get_H(T, units)`, `get_S(T, units)`, `get_G(T, units)`, and `get_Cp(T, units)`.
